consumer.queue.message.dead.letter: consumer_queue_message_dead_letter

spring:
  mvc:
    dispatch-options-request=true:
  datasource:
    url: 'jdbc:postgresql://ta-db.cqecl36zqdfl.us-east-1.rds.amazonaws.com:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
logging:
  level.loggers.org.skife.jdbi.v2: TRACE
cloud.aws:
  stack.auto: false
  region:
    static: us-east-1
  credentials:
    accessKey: AKIA4EQKCAN4CKAGVGWS
    secretKey: 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
---

spring:
  profiles: test
  datasource:
    url: 'jdbc:postgresql://localhost:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: prod
  datasource:
    url: 'jdbc:postgresql://ta-db.cqecl36zqdfl.us-east-1.rds.amazonaws.com:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver