consumer.queue.message.dead.letter: consumer_queue_message_dead_letter

spring:
  mvc:
    dispatch-options-request=true:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
logging:
  level.loggers.org.skife.jdbi.v2: TRACE
cloud.aws:
  stack.auto: false
  region:
    static: us-east-2
  credentials:
    accessKey: AKIA4EQKCAN4KLX33YMT
    secretKey: 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
---

spring:
  profiles: test
  datasource:
    url: 'jdbc:postgresql://localhost:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: prod
  datasource:
    url: 'jdbc:postgresql://192.168.15.6:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver