consumer.queue.message: consumer_queue_message
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/trainingaws?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver
server:
  port: 2011
logging:
  level.loggers.org.skife.jdbi.v2: TRACE
cloud.aws:
  stack.auto: false
  region:
    static: 
  credentials:
    accessKey: 
    secretKey: 
