consumer.queue.message: consumer_queue_message
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/marketplace?currentSchema=trainingaws'
    username: trainingaws
    password: trainingaws
    driver-class-name: org.postgresql.Driver
server:
  port: 2011
logging:
  level.loggers.org.skife.jdbi.v2: TRACE
cloud.aws:
  stack.auto: false
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID:AKIAJEDAAIVKZJRI7ASQ}
    secretKey: ${AWS_SECRET_ACCESS_KEY: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}
  region:
    static: us-east-1
#  region:
#    static:
#  credentials:
#    accessKey:
#    secretKey:
